---
title: "DRG"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
options(scipen=999)
library(ggplot2)
library(scales)
library(tidyverse)
library(cluster)
library(arules)
library(dplyr)
library(splitstackshape)
library(arulesViz)
library(fpc)
library(clusterSim)
library(stats)
library(rpart)
library(rpart.plot)
library(party)
library(partykit)
library(caret)
library(VIM)
library(randomForest)
library(e1071)
library(ROCR)
library(Matrix)
library(arules)
library(arulesViz)
library(knitr)
```
```{r}
tfidf_dm_df <- read.csv("C:/Users/ak055384/Documents/HIMClaims/Visualization/proc_document_matrix.csv")
dim(tfidf_dm_df)
```
```{r}
set.seed(123)
clusters_300 <- kmeans(tfidf_dm_df, centers=10) 
plotcluster(tfidf_dm_df, clusters_300$cluster, main="k=10")
# Cluster size
clusters_300$size
# Within Sum of Squares
clusters_300$withinss
# Between Sum of Squares
clusters_300$betweenss
# Total Sum of Squares
clusters_300$totss
```
```{r}
claims_df <- read.csv("C:/Users/ak055384/Documents/DRGs/Association/Claims.csv")
dim(claims_df)
```
```{r}
claims_df <- claims_df[13:18]
head(claims_df)
dim(claims_df)
```
A single row 3:
```{r}
#length(train_df)
claims_df[13,]
```
```{r}
test <- claims_df[13,]
paste(unlist(test[test != ""]), collapse = ',')
```
```{r}
nrow(claims_df)
```

### Convert diagnosis to transactions
```{r}
patientDiag <- matrix(0, nrow = nrow(claims_df), ncol = 1)
for (i in 1:nrow(claims_df)) {
    singleRow <- claims_df[i,]
    singleline <- paste(unlist(singleRow[singleRow != ""]), collapse = ',')
    patientDiag[i,] <- singleline
}
```
#### results size
```{r}
head(patientDiag)
dim(patientDiag)
```
```{r}
write(patientDiag, file="C:/Users/ak055384/Documents/DRGs/Association/basket/proc_basket") 
diag_basket<-read.transactions("C:/Users/ak055384/Documents/DRGs/Association/basket/proc_basket", format="basket", sep=",")
```

```{r}
dim(diag_basket)
freq_diag_basket_df <- as.data.frame(itemFrequency(diag_basket))
kable(freq_diag_basket_df)
```
```{r fig.width=8, fig.height=8}
itemFrequencyPlot(diag_basket, topN=20, names=TRUE)
```

```{r fig.width=8, fig.height=8}
itemFrequencyPlot(diag_basket, support = 0.01)
```
```{r}
image(diag_basket)
image(diag_basket[1:5])
image(sample(diag_basket, 100))
```


```{r}
summary(diag_basket)
```


### Run Apriori on user transaction.
```{r}
diagnosis_basket_rules <- apriori(diag_basket, parameter = list(support = 0.0001, confidence = 0.7, minlen = 2)) 
print(diagnosis_basket_rules) 
summary(diagnosis_basket_rules)
```

```{r}
diagnosis_basket_rules_sorted <-sort(diagnosis_basket_rules, by = c("lift", "confidence"))
kable(as(diagnosis_basket_rules_sorted, "data.frame"))
diagnosis_basket_rules_sorted_df <- as(diagnosis_basket_rules_sorted, "data.frame")
write.csv(diagnosis_basket_rules_sorted_df, "C:/Users/ak055384/Documents/DRGs/Association/basket/procedure_basket_rules_sorted.csv")
```